name: 'Ilyas Colombowala, MD, FHRS'
favicon: null
layout_spectrum: 0.14472333528101444
typography_spectrum: 0.76246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a514a'
    - '#d8dce7'
    - '#9ea1b0'
    - '#0a0104'
    - '#cd7552'
  brandStrength: 0.14409707090817392
  lightness: 0.9844834259711206
  saturation: 0.2467009318061173
  rhythmicContrast: 0.07068439782597125
purpose: []
